version: "3.7"
name: hangar

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: hangar
      POSTGRES_USER: hangar
      POSTGRES_PASSWORD: ${HANGAR_DBPASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailslurper:
    platform: linux/amd64
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
      - "1025:1025"

volumes:
  postgres_data:

networks:
  default:
    name: hangar-network
